### ISSUE TITLE
Transaction has a bad signature error

### ISSUE THREAD

**Issue by Kofituo** [paritytech/subxt#1180]
I'm trying to submit extrinsic to the [frontier node](https://github.com/paritytech/frontier/tree/master/template#substrate-frontier-node-template). However, I'm facing an `Invalid Transaction` error with the message `Transaction has a bad signature`. 
Here's my code (adapted from this [example](https://github.com/paritytech/subxt/blob/master/subxt/examples/tx_basic.rs))

main.rs
```rust
#[subxt::subxt(runtime_metadata_path = "metadata.scale")]
pub mod etherconfig {}

use fp_account::{AccountId20, EthereumSignature};
use hex_literal::hex;
use sp_core::ecdsa::Pair as EcdsaPair;
use sp_core::Pair;
use subxt::config::polkadot::PolkadotExtrinsicParams;
use subxt::config::substrate::BlakeTwo256;
use subxt::tx::Signer;
use subxt::utils::H256;
use subxt::{Config, OnlineClient, SubstrateConfig};
#[tokio::main]
async fn main() {
    // Create a new API client, configured to talk to Polkadot nodes.
    let api = OnlineClient::<EthereumConfig>::new().await.unwrap();

    // Build a balance transfer extrinsic.
    let dest = etherconfig::runtime_types::fp_account::AccountId20(EthPair::bob().public_key.0);
    let balance_transfer_tx = etherconfig::tx()
        .balances()
        .transfer_allow_death(dest, 10_000);

    // Submit the balance transfer extrinsic from Alice, and wait for it to be successful
    // and in a finalized block. We get back the extrinsic events if all is well.
    let from = EthPair::alice();
    let events = api
        .tx()
        .sign_and_submit_then_watch_default(&balance_transfer_tx, &from)
        .await
        .unwrap()
        .wait_for_finalized_success()
        .await
        .unwrap();

    // Find a Transfer event and print it.
    let transfer_event = events.find_first::<etherconfig::balances::events::Transfer>().unwrap();
    if let Some(event) = transfer_event {
        println!("Balance transfer success: {event:?}");
    }
}

pub enum EthereumConfig {}

impl Config for EthereumConfig {
    type Hash = H256;
    type AccountId = AccountId20;
    type Address = Self::AccountId;
    type Signature = EthereumSignature;
    type Hasher = BlakeTwo256;
    type Header = <SubstrateConfig as Config>::Header;
    type ExtrinsicParams = PolkadotExtrinsicParams<Self>;
}

impl EthPair {
    pub fn alice() -> EthPair {
        EthPair {
            public_key: AccountId20::from(hex!("f24ff3a9cf04c71dbc94d0b566f7a27b94566cac")),
            pair: EcdsaPair::from_seed(&hex!(
                "5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133"
            )),
        }
    }
    pub fn bob() -> EthPair {
        EthPair {
            public_key: AccountId20::from(hex!("3cd0a705a2dc65e5b1e1205896baa2be8a07c6e0")),
            pair: EcdsaPair::from_string("//Bob", None).expect("Bob is valid"),
        }
    }
}

pub struct EthPair {
    pub public_key: AccountId20,
    pub pair: EcdsaPair,
}

impl Signer<EthereumConfig> for EthPair {
    fn account_id(&self) -> <EthereumConfig as Config>::AccountId {
        self.public_key
    }

    fn address(&self) -> <EthereumConfig as Config>::Address {
        AccountId20::from(self.pair.public())
    }

    fn sign(&self, signer_payload: &[u8]) -> <EthereumConfig as Config>::Signature {
        EthereumSignature::new(self.pair.sign(signer_payload))
    }
}
```

In cargo.toml
```toml
[package]
name = "testing-extrinsic"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
subxt = "0.31.0"
subxt-signer = "0.31.0"
fp-account = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.43"}
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
```

Here's the error message:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
     Running `target/debug/testing-extrinsic`
thread 'main' panicked at src/main.rs:31:10:
called `Result::unwrap()` on an `Err` value: Rpc(ClientError(Call(Custom(ErrorObject { code: ServerError(1010), message: "Invalid Transaction", data: Some(RawValue("Transaction has a bad signature")) }))))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/58e967a9cc3bd39122e8cb728e8cec6e3a4eeef2/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at /rustc/58e967a9cc3bd39122e8cb728e8cec6e3a4eeef2/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/58e967a9cc3bd39122e8cb728e8cec6e3a4eeef2/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/58e967a9cc3bd39122e8cb728e8cec6e3a4eeef2/library/core/src/result.rs:1077:23
   4: testing_extrinsic::main::{{closure}}
             at ./src/main.rs:27:18
   5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/kofiotuo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
   6: tokio::runtime::coop::with_budget
             at /Users/kofiotuo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at /Users/kofiotuo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
   8: tokio::runtime::park::CachedParkThread::block_on
             at /Users/kofiotuo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
   9: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/kofiotuo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/kofiotuo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  11: tokio::runtime::context::runtime::enter_runtime
             at /Users/kofiotuo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/kofiotuo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  13: tokio::runtime::runtime::Runtime::block_on
             at /Users/kofiotuo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
  14: testing_extrinsic::main
             at ./src/main.rs:38:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/58e967a9cc3bd39122e8cb728e8cec6e3a4eeef2/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

By the way this works with the Polkadot Ui so I'm assuming there's something wrong with how I've implemented the `Signer`

**Comment by lexnv** [comment]
I've managed to reproduce this behavior with frontier on [commit 789fa512](https://github.com/paritytech/frontier/commit/789fa512b412d607bfaf6bcc7bb6863199675c86).

Inspecting the metadata of the frontier-node, resulted in the frontier-signer being indeed the one you provided:

```
{
  "id": 166,
  "type": {
    "path": [
      "fp_account",
      "EthereumSignature"
    ],
    "def": {
      "composite": {
        "fields": [
          {
            "type": 167,
            "typeName": "ecdsa::Signature"
          }
        ]
      }
    }
  }
}
```

Implemented a custom signer, just to filter out any inconsistencies by different crate versions:

```rust
#[derive(Debug, Encode)]
pub struct CustomSignature([u8; 65]);

    fn sign(&self, signer_payload: &[u8]) -> <EthereumConfig as Config>::Signature {
        let secret = subxt_signer::SecretUri::from_str("//Bob").expect("valid");
        let key_pair = subxt_signer::ecdsa::Keypair::from_uri(&secret).expect("valid");
        let signtaure = key_pair.sign(signer_payload);
        CustomSignature(signtaure.0)
    }
    
```

`signed_extensions` are identical between the polkadot-metadata and frontier-metadata 

Will continue to dig into this, let me know of any updates from your side just to not do any double work here :D thanks

**Comment by Kofituo** [comment]
@lexnv Perhaps it's got to do with the `ExtrinsicParams` since Polkadot extrisincs use MultiAddress of AccountI32.

**Comment by jsdw** [comment]
None of the signed extensions care about the account ID format, but we do encode the address as part of a signed transaction, and in your config above `Config::Address == Config::AccountId == AccountId20`. It'd be good to confirm that that is correct. (Possibly bey deliberately changing one of those to be wrong, or tweaking how Subxt encodes the address into the TX, and seeing whether the error you get back is still "Bad Signature" or something else now)

**Comment by Kofituo** [comment]
@jsdw Yes both the AccountId and Address are the same in the frontier template node.
But what do you mean by "hash public key before comparing"? Do you mean on the subxt side or the frontier side? 

Note that transactions work fine with the polkadot ui. And both the signer and the computed pubkey (link [here](https://github.com/paritytech/frontier/blob/789fa512b412d607bfaf6bcc7bb6863199675c86/primitives/account/src/lib.rs#L171)) are the same when using the ui but somehow different when using subxt

**Comment by jsdw** [comment]
> But what do you mean by "hash public key before comparing"? Do you mean on the subxt side or the frontier side?

I mean, the verification logic I linked seems to first `keccak_256` has hthe message before verifying it, and then hashes the public key (AccountId20) to compare (ie `AccountId20(H160::from(H256::from(keccak_256(&pubkey))).0)`) so perhaps the signing logic above needs to also be doing something similar when signing the messages to make it align with this (and right now it's not in the cove above)?

> Note that transactions work fine with the polkadot ui. And both the signer and the computed pubkey (link [here](https://github.com/paritytech/frontier/blob/789fa512b412d607bfaf6bcc7bb6863199675c86/primitives/account/src/lib.rs#L171)) are the same when using the ui but somehow different when using subxt

I'm not sure what special logic the Polkadot.js UI has for handling these sorts of things (Subxt has no special handling for `AccountID20`'s and the signing of them), but definitely a place to dig into is what that is doing versus what the Subxt logic above is doing.

**Comment by lexnv** [comment]
Some differences in producing the extrinsic `system::set_code(vec![ 0 ])` from Alith account: 

```
Subxt
0x7501 84
signer = f24ff3a9cf04c71dbc94d0b566f7a27b94566cac
83aa07fab2c4aba3d9c2891086bace229d08f68c2904fd89948e14e43475bb0269dbbc0273cd553efd09aa248bdd46733863605a8ad1662fe75db538cb576ccf00000000
call_index = 0002
code = 0400

PolkadotJS
0x7901 84
signer = f24ff3a9cf04c71dbc94d0b566f7a27b94566cac
signature = 0058f4eb69e714153941d32b5c4911267ba77d2d892ea6907fd70ca264c1d4e74413a4c69539e28953f4b9988183b7aa1a33ead2fa6e05b568d1d6e66ec242f000
25000000
call_index = 0002
code = 0400
```

I've looked a bit into how the accounts are generated, which seems fine to me:

```rust
pub struct EthPair {
    pub account_id: AccountId20,
    pub pair: EcdsaPair,
}

impl EthPair {
    pub fn from_pair(pair: EcdsaPair) -> EthPair {
        let public_key = pair.public();

        let account_id = {
            let decompressed = libsecp256k1::PublicKey::parse_compressed(&public_key.0)
                .expect("Wrong compressed public key provided")
                .serialize();

            let mut m = [0u8; 64];
            m.copy_from_slice(&decompressed[1..65]);
            let account = H160::from(H256::from(sp_core::hashing::keccak_256(&m)));
            let account_id: [u8; 20] = account.into();
            AccountId20::from(account_id)
        };

        println!("Account ID {:?}", account_id);

        EthPair { account_id, pair }
    }

    pub fn from_string(s: &str) -> EthPair {
        let pair = EcdsaPair::from_string(s, None).expect("valid");
        EthPair::from_pair(pair)
    }
}

```

With a note that I've been using Alith (seed `5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133`) and Baltathar (`8075991ce870b93a8870eca0c0f91913d12f47948ca0fd25b49c6fa7cdbeee8b`).


I've also verified the signature after producing it:

```rust
fn sign(&self, signer_payload: &[u8]) -> <EthereumConfig as Config>::Signature {
        println!("Signing message payload {:?}", signer_payload);
        let signature = self.pair.sign(signer_payload);
        println!("Signature: {:?}", signature);

        // Verify the signature
        {
            let m = blake2_256(signer_payload);
            let validity = match sp_io::crypto::secp256k1_ecdsa_recover(signature.as_ref(), &m) {
                Ok(pubkey) => {
                    let found_account = AccountId20(H160::from(H256::from(keccak_256(&pubkey))).0);
                    println!("Account included in signature: {:?}", found_account);
                    found_account == self.account_id
                }
                Err(sp_io::EcdsaVerifyError::BadRS) => {
                    false
                }
                Err(sp_io::EcdsaVerifyError::BadV) => {
                    false
                }
                Err(sp_io::EcdsaVerifyError::BadSignature) => {
                    false
                }
            };

            println!("Signature validity: {:?}", validity)
        }

        EthereumSignature::new(self.pair.sign(signer_payload))
```

However, my verification uses `blake2_256` instead of `keccak_256` frontier hashing of the signed message!

**Comment by lexnv** [comment]
The signature must be calculated the same way, using `keccak_256`:

```rust
        let message = keccak_256(signer_payload);
        let signature = self.pair.sign_prehashed(&message);
```

Here is a working example:

```rust
#[subxt::subxt(runtime_metadata_path = "metadata.scale")]
pub mod etherconfig {}

use fp_account::{AccountId20, EthereumSignature};
use hex_literal::hex;
use sp_core::ecdsa::Pair as EcdsaPair;
use sp_core::{keccak_256, Pair};
use subxt::config::polkadot::PolkadotExtrinsicParams;
use subxt::tx::Signer;
use subxt::utils::{H160, H256};

use subxt::{Config, OnlineClient, SubstrateConfig};
#[tokio::main]
async fn main() {
    // Create a new API client, configured to talk to Polkadot nodes.
    let api = OnlineClient::<EthereumConfig>::new().await.unwrap();

    // Build a balance transfer extrinsic.
    let dest = etherconfig::runtime_types::fp_account::AccountId20(EthPair::bob().account_id.0);
    let balance_transfer_tx = etherconfig::tx()
        .balances()
        .transfer_allow_death(dest, 10_000);

    let from = EthPair::alice();

    let tx = api
        .tx()
        .create_signed(&balance_transfer_tx, &from, Default::default())
        .await
        .unwrap();

    println!("encoded tx: {:?}", hex::encode(tx.encoded()));

    // Submit the balance transfer extrinsic from Alice, and wait for it to be successful
    // and in a finalized block. We get back the extrinsic events if all is well.
    let events = api
        .tx()
        .sign_and_submit_then_watch_default(&balance_transfer_tx, &from)
        .await
        .unwrap()
        .wait_for_finalized_success()
        .await
        .unwrap();

    // Find a Transfer event and print it.
    let transfer_event = events
        .find_first::<etherconfig::balances::events::Transfer>()
        .unwrap();
    if let Some(event) = transfer_event {
        println!("Balance transfer success: {event:?}");
    }
}

pub enum EthereumConfig {}

impl Config for EthereumConfig {
    type Hash = <SubstrateConfig as Config>::Hash;
    type AccountId = AccountId20;
    type Address = Self::AccountId;
    type Signature = EthereumSignature;
    type Hasher = <SubstrateConfig as Config>::Hasher;
    type Header = <SubstrateConfig as Config>::Header;
    type ExtrinsicParams = PolkadotExtrinsicParams<Self>;
}

impl EthPair {
    pub fn alice() -> EthPair {
        let pair = EcdsaPair::from_seed(&hex!(
            "5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133"
        ));
        EthPair::from_pair(pair)
    }
    pub fn bob() -> EthPair {
        let pair = EcdsaPair::from_seed(&hex!(
            "8075991ce870b93a8870eca0c0f91913d12f47948ca0fd25b49c6fa7cdbeee8b"
        ));
        EthPair::from_pair(pair)
    }
}

pub struct EthPair {
    pub account_id: AccountId20,
    pub pair: EcdsaPair,
}

impl EthPair {
    pub fn from_pair(pair: EcdsaPair) -> EthPair {
        let public_key = pair.public();

        let account_id = {
            let decompressed = libsecp256k1::PublicKey::parse_compressed(&public_key.0)
                .expect("Wrong compressed public key provided")
                .serialize();

            let mut m = [0u8; 64];
            m.copy_from_slice(&decompressed[1..65]);
            let account = H160::from(H256::from(sp_core::hashing::keccak_256(&m)));
            let account_id: [u8; 20] = account.into();
            AccountId20::from(account_id)
        };

        println!("Account ID {:?}", account_id);

        EthPair { account_id, pair }
    }

    pub fn from_string(s: &str) -> EthPair {
        let pair = EcdsaPair::from_string(s, None).expect("valid");
        EthPair::from_pair(pair)
    }
}

impl Signer<EthereumConfig> for EthPair {
    fn account_id(&self) -> <EthereumConfig as Config>::AccountId {
        self.account_id
    }

    fn address(&self) -> <EthereumConfig as Config>::Address {
        self.account_id
    }

    fn sign(&self, signer_payload: &[u8]) -> <EthereumConfig as Config>::Signature {
        println!("Signing message payload {:?}", signer_payload);
        let message = keccak_256(signer_payload);
        let signature = self.pair.sign_prehashed(&message);

        println!("Signature: {:?}", signature);

        // Verify the signature
        {
            let m = keccak_256(signer_payload);
            let validity = match sp_io::crypto::secp256k1_ecdsa_recover(signature.as_ref(), &m) {
                Ok(pubkey) => {
                    let found_account = AccountId20(H160::from(H256::from(keccak_256(&pubkey))).0);
                    println!("Account included in signature: {:?}", found_account);
                    found_account == self.account_id
                }
                Err(sp_io::EcdsaVerifyError::BadRS) => {
                    println!("Error recovering: Incorrect value of R or S");
                    false
                }
                Err(sp_io::EcdsaVerifyError::BadV) => {
                    println!("Error recovering: Incorrect value of V");
                    false
                }
                Err(sp_io::EcdsaVerifyError::BadSignature) => {
                    println!("Error recovering: Invalid signature");
                    false
                }
            };

            println!("Signature validity: {:?}", validity)
        }

        EthereumSignature::new(signature)
    }
}
```

**Comment by jsdw** [comment]
> Here is a working example

Working as in, this no longer leads to a "bad signature" error? :)

**Comment by lexnv** [comment]
Yep, it results in:

```
Account included in signature: 0xf24ff3a9cf04c71dbc94d0b566f7a27b94566cac
Signature validity: true
Balance transfer success: Transfer { from: AccountId20([242, 79, 243, 169, 207, 4, 199, 29, 188, 148, 208, 181, 102, 247, 162, 123, 148, 86, 108, 172]), to: AccountId20([60, 208, 167, 5, 162, 220, 101, 229, 177, 225, 32, 88, 150, 186, 162, 190, 138, 7, 198, 224]), amount: 10000 }
```

**Comment by lexnv** [comment]
It is my understanding that the `Hasher` component should be used by the runtime, which I'm not entirely sure if frontier is using it or not.
Headers also use `BlakeTwo256` for substrate-chains, which I would expect changing to `Keccak256` would result in different hashes.
The `Keccak256` might be just an implementation detail for signatures.

I guess the best way to be sure of it would be having something similar to: 

```rust
#[derive(Debug, Clone, Copy, PartialEq, Eq, Encode)]
pub struct Keccak256;

impl Hasher for Keccak256 {
    type Output = H256;
    fn hash(s: &[u8]) -> Self::Output {
        keccak_256(s).into()
    }
}
```

**Comment by Kofituo** [comment]
Okay thanks so much for the help! I'm closing the issue now.

**Comment by jsdw** [comment]
I checked and the frontier chain has `BlakeTwo256` configured as its `Hasher` type, so yeah the Keccak256 thing in the signature is just a sig specific implementation detail by the looks of it :)

**Comment by Kofituo** [comment]
Got it 👍
