### ISSUE TITLE
cmake error on Debian

### ISSUE THREAD

**Issue by TomaszWaszczyk** [paritytech/subxt#1322]
Has anyone else the error on Debian?

```
[ERROR project_model::workspace] cyclic deps: subxt_signer(Idx::<CrateData>(443)) -> subxt(Idx::<CrateData>(413)), alternative path: subxt(Idx::<CrateData>(413)) -> subxt_signer(Idx::<CrateData>(443))
[ERROR project_model::workspace] cyclic deps: subxt_signer(Idx::<CrateData>(443)) -> subxt(Idx::<CrateData>(413)), alternative path: subxt(Idx::<CrateData>(413)) -> subxt_signer(Idx::<CrateData>(443))
[ERROR rust_analyzer::main_loop] FetchBuildDataError:
error: failed to run custom build command for `wabt-sys v0.8.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/tomek/workspaces/subxt/target/debug/build/wabt-sys-e578ad294281b8b2/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=WABT_CXXSTDLIB
  cargo:rerun-if-env-changed=CXXSTDLIB
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/home/tomek/workspaces/subxt/target/debug/build/wabt-sys-982fcdc473d3658b/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/tomek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wabt-sys-0.8.0/wabt" "-DBUILD_TESTS=OFF" "-DBUILD_TOOLS=OFF" "-DCMAKE_INSTALL_PREFIX=/home/tomek/workspaces/subxt/target/debug/build/wabt-sys-982fcdc473d3658b/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  thread 'main' panicked at /home/tomek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
     1: core::panicking::panic_fmt
               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
     2: cmake::fail
     3: cmake::run
     4: cmake::Config::build
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


[ERROR project_model::workspace] cyclic deps: subxt_signer(Idx::<CrateData>(443)) -> subxt(Idx::<CrateData>(413)), alternative path: subxt(Idx::<CrateData>(413)) -> subxt_signer(Idx::<CrateData>(443))
```

Probably installation of `cmake` should help to solve the error.

**Comment by tadeohepperle** [comment]
Hey @TomaszWaszczyk, could this maybe be related to [this issue](https://github.com/paritytech/substrate/issues/6945)? It also shows an error for cyclic dependencies on the subxt-side of things, but I do not think this is related. We have not encountered this issue with wabt-sys before.

**Comment by jsdw** [comment]
> Probably installation of cmake should help to solve the error.

Let us know whether this does solve the issue :)

**Comment by TomaszWaszczyk** [comment]
On the day when I was making this issue, installation of `cmake` did not help, but today it helps.
