### ISSUE TITLE
Can't make transactions against 0.9.28 chains related to ChargeAssetTxPayment

### ISSUE THREAD

**Issue by drewstone** [paritytech/subxt#675]
# Overview
Running our client/integration tests against our 0.9.28 runtime throws an error.
- Subxt version `0.24`

## Steps to reproduce:
1. Clone `https://github.com/webb-tools/protocol-substrate`
2. Build: `cargo build --release`
3. Run: `./target/release/webb-standalone-node --dev`
4. Export metadata to client: `subxt metadata -f bytes > client/metadata/protocol_substrate_runtime.scale`
6. Test client: `cd client && cargo test --release`

## Logs from integration test execution
```
Error: Rpc(RpcError("RPC call failed: ErrorObject { code: ServerError(1002), message: \"Verification Error: Runtime error: Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Could not decode `ChargeAssetTxPayment::asset_id`:\\n\\tunexpected first byte decoding Option\\n\", data: Some(RawValue(\"RuntimeApi(\\\"Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Could not decode `ChargeAssetTxPayment::asset_id`:\\\\n\\\\tunexpected first byte decoding Option\\\\n\\\")\")) }"))
test test_mixer ... FAILED
Error: Rpc(RpcError("RPC call failed: ErrorObject { code: ServerError(1002), message: \"Verification Error: Runtime error: Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Could not decode `ChargeAssetTxPayment::asset_id`:\\n\\tunexpected first byte decoding Option\\n\", data: Some(RawValue(\"RuntimeApi(\\\"Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Could not decode `ChargeAssetTxPayment::asset_id`:\\\\n\\\\tunexpected first byte decoding Option\\\\n\\\")\")) }"))
test test_vanchor ... FAILED
```

## Logs from the node
```
Version: 1.0.0-cd1a92c1-aarch64-macos

   0: backtrace::capture::Backtrace::create
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:702:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:588:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/sys_common/backtrace.rs:138:18
   6: rust_begin_unwind
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:584:5
   7: core::panicking::panic_fmt
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/core/src/panicking.rs:142:14
   8: webb_standalone_runtime::api::dispatch
   9: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  10: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  11: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
  12: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  13: <webb_standalone_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::__runtime_api_internal_call_api_at
  14: sc_transaction_pool::api::validate_transaction_blocking
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  18: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  19: tokio::runtime::task::raw::poll
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
  22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/alloc/src/boxed.rs:1951:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/alloc/src/boxed.rs:1951:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/sys/unix/thread.rs:108:17
  23: _pthread_from_mach_thread_np


Thread 'tokio-runtime-worker' panicked at 'Bad input data provided to validate_transaction: Could not decode `ChargeAssetTxPayment::asset_id`:
unexpected first byte decoding Option
', standalone/runtime/src/lib.rs:1515
```

**Comment by jsdw** [comment]
Also FYI:

`git clone https://github.com/webb-tools/protocol-substrate` I can do, but there doesn't seem to exist any `drew/big-endian` branch on github; perhaps you need to push it?

**Comment by drewstone** [comment]
@jsdw thanks for the response, we'll investigate this. The PR was merged to main/master so you should be able to just use the default branch now.
